param(
    [string[]]$ProjectPaths = @(
        "C:\Users\JohnKim\Documents\Codex\2026-05-08\repo-github-codex-chatgpt-source-of",
        "C:\Users\JohnKim\Documents\New project",
        "C:\Users\JohnKim\Documents\New project 2",
        "C:\Users\JohnKim\Documents\New project 3",
        "C:\Users\JohnKim\Documents\Codex\2026-05-08\agents-md-role-you-are-working"
    ),
    [string]$OutputPath = "docs/realtime-repo-status.md"
)

$ErrorActionPreference = "Continue"

function Run-Git {
    param(
        [string]$RepoPath,
        [string[]]$GitArgs
    )

    $result = & git -C $RepoPath @GitArgs 2>$null
    if ($LASTEXITCODE -ne 0) {
        return ""
    }

    return ($result | Out-String).Trim()
}

function Escape-MdCell {
    param([string]$Value)
    if ([string]::IsNullOrWhiteSpace($Value)) {
        return "None"
    }
    return ($Value -replace "\|", "\|" -replace "`r?`n", "<br>")
}

$now = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"
$lines = New-Object System.Collections.Generic.List[string]

$lines.Add("# Real-Time Repo Status")
$lines.Add("")
$lines.Add("Generated: $now")
$lines.Add("")
$lines.Add("This file is generated by `scripts/update-project-status.ps1` so ChatGPT and Codex can quickly understand the current repo state.")
$lines.Add("")
$lines.Add("| Path | Git repo | Branch | Remote | Latest commit | Working tree |")
$lines.Add("| --- | --- | --- | --- | --- | --- |")

foreach ($projectPath in $ProjectPaths) {
    $exists = Test-Path -LiteralPath $projectPath

    if (-not $exists) {
        $safePath = Escape-MdCell $projectPath
        $lines.Add("| $safePath | Missing path | None | None | None | None |")
        continue
    }

    $inside = Run-Git -RepoPath $projectPath -GitArgs @("rev-parse", "--is-inside-work-tree")

    if ($inside -ne "true") {
        $safePath = Escape-MdCell $projectPath
        $lines.Add("| $safePath | No | None | None | None | Not a git repository |")
        continue
    }

    $branch = Run-Git -RepoPath $projectPath -GitArgs @("branch", "--show-current")
    $remote = Run-Git -RepoPath $projectPath -GitArgs @("remote", "-v")
    $latest = Run-Git -RepoPath $projectPath -GitArgs @("log", "-1", "--oneline")
    $status = Run-Git -RepoPath $projectPath -GitArgs @("status", "--short", "--branch")

    $safePath = Escape-MdCell $projectPath
    $safeBranch = Escape-MdCell $branch
    $safeRemote = Escape-MdCell $remote
    $safeLatest = Escape-MdCell $latest
    $safeStatus = Escape-MdCell $status

    $lines.Add("| $safePath | Yes | $safeBranch | $safeRemote | $safeLatest | $safeStatus |")
}

$lines.Add("")
$lines.Add("## Operating Notes")
$lines.Add("")
$lines.Add("- `main` should be the stable truth once a project is published.")
$lines.Add("- Codex work should happen on feature branches and be reviewed through PRs.")
$lines.Add("- Any row with no remote is not yet connected to GitHub.")
$lines.Add("- Any row with no latest commit has not established a stable baseline.")

$outputDir = Split-Path -Parent $OutputPath
if ($outputDir -and -not (Test-Path -LiteralPath $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir | Out-Null
}

$lines | Set-Content -Path $OutputPath -Encoding UTF8
Write-Output "Updated $OutputPath"
